// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8jV_C21RIu1uQhy26vty-8_mKiBfkowU',
    appId: '1:287861806886:web:8d3427e222359ba8b713e7',
    messagingSenderId: '287861806886',
    projectId: 'flutter-project-b83e9',
    authDomain: 'flutter-project-b83e9.firebaseapp.com',
    storageBucket: 'flutter-project-b83e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABubxxn7xcLCPmqRKphsFDsiJ7PKcLBFU',
    appId: '1:287861806886:android:64ba0e800126cb9fb713e7',
    messagingSenderId: '287861806886',
    projectId: 'flutter-project-b83e9',
    storageBucket: 'flutter-project-b83e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqdlSPzWHzFrYCP1I5xXn30FvVGFFems',
    appId: '1:287861806886:ios:502452ac7d9c30e8b713e7',
    messagingSenderId: '287861806886',
    projectId: 'flutter-project-b83e9',
    storageBucket: 'flutter-project-b83e9.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );
}
